# Generated by Django 3.2.8 on 2021-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('ic_no', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='IcNo')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('address1', models.CharField(max_length=100, verbose_name='Alamat 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Alamat 2')),
                ('city', models.CharField(max_length=20, verbose_name='Bandar')),
                ('mukim', models.CharField(max_length=20, verbose_name='Mukim')),
                ('parlimen', models.CharField(max_length=20, verbose_name='Parlimen')),
                ('state', models.CharField(max_length=20, verbose_name='Negeri')),
                ('poskod', models.IntegerField(verbose_name='Poskod')),
                ('income', models.IntegerField(verbose_name='Income')),
            ],
        ),
    ]
