# Generated by Django 3.2.8 on 2021-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
